FROM alpine:3.21@sha256:a8560b36e8b8210634f77d9f7f9efd7ffa463e380b75e2e74aff4511df3ef88c AS build
ARG XEN_VERSION=4.21
ARG XEN_BRANCH=isol8/$XEN_VERSION
ARG XEN_REPO=https://github.com/noeljackson/xen.git
WORKDIR /usr/src

# build dependencies
RUN apk update && apk add build-base git flex bison perl bash coreutils argp-standalone attr-dev curl-dev linux-headers openssl-dev python3-dev xz-dev ocaml ocamlbuild ocaml-ocamldoc dev86 iasl util-linux-dev py3-setuptools ncurses-dev spice-dev xz-dev yajl-dev zlib-dev zstd-dev perl-dev openssl-dev e2fsprogs-dev curl-dev attr-dev dtc-dev

# patch management infrastructure
COPY ./apply-patches.sh ./apply-patches.sh
COPY ./patches ./patches

# check out xen sources
ENV XEN_VERSION=${XEN_VERSION}
ENV XEN_BRANCH=${XEN_BRANCH}
ENV XEN_REPO=${XEN_REPO}
RUN git clone -b "$XEN_BRANCH" $XEN_REPO

WORKDIR /usr/src/xen

# patch build system
RUN sh /usr/src/apply-patches.sh ${XEN_VERSION} oxenstored

# configure Xen build system
RUN ./configure --prefix=/usr --disable-xen --enable-tools --disable-stubdom --disable-docs

# build oxenstore
ENV CFLAGS="-O2 -Wall -static -fPIC"
ENV LDFLAGS="-static"
RUN make -j$(nproc) -C tools/include all V=1 nosharedlibs=y
RUN make -j$(nproc) -C tools/libs/call all V=1 nosharedlibs=y
RUN make -j$(nproc) -C tools/libs/ctrl all V=1 nosharedlibs=y
RUN make -j$(nproc) -C tools/libs/devicemodel all V=1 nosharedlibs=y
RUN make -j$(nproc) -C tools/libs/foreignmemory all V=1 nosharedlibs=y
RUN make -j$(nproc) -C tools/libs/gnttab all V=1 nosharedlibs=y
RUN make -j$(nproc) -C tools/libs/guest all V=1 nosharedlibs=y
RUN make -j$(nproc) -C tools/libs/evtchn all V=1 nosharedlibs=y
RUN make -j$(nproc) -C tools/libs/toolcore all V=1 nosharedlibs=y
RUN make -j$(nproc) -C tools/libs/toollog all V=1 nosharedlibs=y
RUN make -j$(nproc) -C tools/ocaml all nosharedlibs=y && strip tools/ocaml/xenstored/oxenstored
COPY ./oxenstored.service /output/usr/lib/systemd/system/oxenstored.service
RUN ln -s oxenstored.service /output/usr/lib/systemd/system/xenstored.service

## copy final oxenstored into a scratch image
FROM scratch AS final
COPY --from=build /usr/src/xen/tools/ocaml/xenstored/oxenstored /usr/sbin/oxenstored
COPY --from=build /usr/src/xen/tools/ocaml/xenstored/oxenstored.conf /etc/xen/oxenstored.conf
COPY --from=build /output/usr/lib/systemd/system /usr/lib/systemd/system
