name: release
on:
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * 1"
permissions:
  contents: read
  packages: write
  id-token: write
jobs:
  build:
    runs-on: edera-large
    strategy:
      fail-fast: false
      matrix:
        release:
        - 4.19.0
        - 4.19.1
        - 4.20.0
        - 4.20.1
        - 4.21
        component:
        - xen
        - oxenstored
        - qemu-xen
    name: oci build ${{ matrix.component }}-${{ matrix.release }}
    steps:
    - uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
      with:
        egress-policy: audit
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        submodules: recursive
    - uses: sigstore/cosign-installer@faadad0cce49287aee09b3a48701e75088a2c6ad # v4.0.0
    - uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3.7.0
    - uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0
    - uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

      # these are all built against upstream RELEASE-X.X.X branches, and patch them.
      # Starting with 4.21, we build against `edera/X.X.X` branches, which integrated patches.
    - name: Determine XEN_BRANCH
      id: branch
      run: |
        VERSION="${{ matrix.release }}"
        MAJOR_MINOR=$(echo "$VERSION" | cut -d. -f1,2)

        if [ "$(printf '%s\n' "4.20" "$MAJOR_MINOR" | sort -V | head -n1)" = "$MAJOR_MINOR" ] && [ "$MAJOR_MINOR" != "4.21" ]; then
          echo "name=RELEASE-${VERSION}" >> $GITHUB_OUTPUT
        else
          echo "name=edera/${VERSION}" >> $GITHUB_OUTPUT
        fi

    - uses: docker/build-push-action@601a80b39c9405e50806ae38af30926f9d957c47 # v6.19.1
      id: push-step
      with:
        file: ./Dockerfile.${{ matrix.component }}
        platforms: linux/amd64,linux/aarch64
        tags: ghcr.io/edera-dev/${{ matrix.component }}:${{ matrix.release }}
        build-args: |
          XEN_VERSION=${{ matrix.release }}
          XEN_BRANCH=${{ steps.branch.outputs.name }}
        push: true
    - name: Sign the image
      env:
        DIGEST: ${{ steps.push-step.outputs.digest }}
        TAGS: ghcr.io/edera-dev/${{ matrix.component }}:${{ matrix.release }}
        COSIGN_EXPERIMENTAL: "true"
      run: cosign sign --yes "${TAGS}@${DIGEST}"
